name: Test
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: Building (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: macos-latest
            target: x86_64-apple-darwin
            use-cross: false
          - os: macos-latest
            target: aarch64-apple-darwin
            use-cross: false
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-20.04
            target: aarch64-unknown-linux-gnu
            use-cross: true

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build
          use-cross: ${{ matrix.job.use-cross }}
          args: --release --locked --target ${{ matrix.job.target }} --features vendored-openssl

  test:
    name: Testing (${{ matrix.job.os }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      matrix:
        job:
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
            use-cross: false

    steps:
      - name: Installing Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          profile: minimal
          override: true
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create projects directory
        run: mkdir ~/Projects
      - name: Cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
          use-cross: ${{ matrix.job.use-cross }}
          args: --locked --target ${{ matrix.job.target }} --features vendored-openssl
